name       : udunits
version    : 2.2.24
release    : 2
source     :
    - ftp://ftp.unidata.ucar.edu/pub/udunits/udunits-2.2.24.tar.gz : 20bac512f2656f056385429a0e44902fdf02fc7fe01c14d56f3c724336177f95
license    : MIT
component  : programming.tools
summary    : C library for units of physical quantities and a unit-definition and value-conversion utility
description: |
    C library for units of physical quantities and a unit-definition and value-conversion utility
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install

    ln -s libudunits2.so "$installdir/%libdir%/libudunits.so"
    ln -s libudunits2.so.0 "$installdir/%libdir%/libudunits.so.0"
    ln -s libudunits2.so.0.1.0 "$installdir/%libdir%/libudunits.so.0.1.0"
