name       : udunits
version    : 2.2.27.6
release    : 5
source     :
    - https://github.com/Unidata/UDUNITS-2/archive/v2.2.27.6.tar.gz : 74fd7fb3764ce2821870fa93e66671b7069a0c971513bf1904c6b053a4a55ed1
license    : MIT
component  : programming.tools
summary    : C library for units of physical quantities and a unit-definition and value-conversion utility
description: |
    C library for units of physical quantities and a unit-definition and value-conversion utility
setup      : |
    %reconfigure --disable-static
build      : |
    %make
install    : |
    %make_install
    ln -s %libdir%/libudunits2.so $installdir/%libdir%/libudunits.so
    ln -s %libdir%/libudunits2.so.0 $installdir/%libdir%/libudunits.so.0
    ln -s %libdir%/libudunits2.so.0.1.0 $installdir/%libdir%/libudunits.so.0.1.0
