name       : udunits
version    : 2.2.20
release    : 1
source     :
    - ftp://ftp.unidata.ucar.edu/pub/udunits/udunits-2.2.20.tar.gz : f10a02014bc6a200d50d8719997bb3a6b3d364de688469d2f7d599688dd9d195
license    : MIT
component  : programming.tools
summary    : C library for units of physical quantities and a unit-definition and value-conversion utility
description: |
    C library for units of physical quantities and a unit-definition and value-conversion utility
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install

    ln -s libudunits2.so "$installdir/%libdir%/libudunits.so"
    ln -s libudunits2.so.0 "$installdir/%libdir%/libudunits.so.0"
    ln -s libudunits2.so.0.1.0 "$installdir/%libdir%/libudunits.so.0.1.0"
